# Build stage
FROM node:22.18.0-alpine AS builder

WORKDIR /app

ENV PAYMENT_WEBHOOK_URL=""

# Copy package files
COPY package*.json ./

# Install dependencies and Nest CLI globally
RUN npm install

# Copy source code
COPY . .

# Build the application
RUN npm run build

# Production stage
FROM node:22.18.0-alpine

WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install

# Copy built application and node_modules
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules

# Expose the port the app runs on
EXPOSE 4000

# Start the application in development mode for hot-reload
CMD ["npm", "run", "start:dev"]
